Name = "vimexx.nl"
Description = ''''''
URL = "https://www.vimexx.nl/"
Code = "vimexx"
Since = "v4.11.0"

Example = '''
VIMEXX_SERVER_BASE_URL="https://api.vimexx.nl" \
VIMEXX_ENDPOINT="/api/v1" \
VIMEXX_USERNAME="you@example.com" \
VIMEXX_PASSWORD=supersecret \
VIMEXX_CLIENT_ID="123" \
VIMEXX_CLIENT_SECRET="abcdef" \
lego --email you@example.com --dns vimexx -d '*.example.com' run
'''

[Configuration]
  [Configuration.Credentials]
    VIMEXX_SERVER_BASE_URL = "Base URL of the server (ex: https://api.vimexx.nl)"
    VIMEXX_ENDPOINT = "Base API (ex: /api/v1 or /apitest/v1)"
    VIMEXX_USERNAME = "Vimexx username (e-mail)"
    VIMEXX_PASSWORD = "Vimexx password"
    VIMEXX_CLIENT_ID = "Vimexx client id"
    VIMEXX_CLIENT_SECRET = "Vimexx client secret"
  [Configuration.Additional]
    VIMEXX_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    VIMEXX_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    VIMEXX_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)"
    VIMEXX_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = ""
